feat/editor slate
notes-org/notes-frontend pull request #8
Opened 2024-03-14 21:20 UTC by berdal84

WIP

Notes:

- "🤖 Slate is currently in beta. Its core API is usable now, but you might need to pull request fixes for advanced use cases. Some of its APIs are not "finalized" and will (breaking) change over time as we find better solutions." (https://docs.slatejs.org/ 03/14/2024)

2024-03-19 13:17 UTC, rjmello requested changes

2024-03-19 13:17 UTC, rjmello commented on src/components/editor/Editor.tsx
> +              <Editable
Can we set the default height of the text box to 150-200px or so?

2024-03-19 13:17 UTC, rjmello commented on src/utils/ApiClient.ts
> +                content: JSON.stringify(note.content) // TODO: allow an object instead of string on the backend API? Would be symetric
JSON is transmitted as a string over HTTP. Thus, we will always need to call `JSON.stringify()`, or a similar function, before sending it to the API.

2024-03-21 00:56 UTC, berdal84 commented on src/utils/ApiClient.ts
> +                content: JSON.stringify(note.content) // TODO: allow an object instead of string on the backend API? Would be symetric
Without a stringify the API rejects the body, a string is expected, not an JSON object.

2024-03-21 00:56 UTC, berdal84 commented on src/components/editor/Editor.tsx
> +              <Editable
Yep, will change that.

2024-03-21 01:17 UTC, berdal84 commented
Just fixed the height on the note editor. I also added a border since it was looking weird with all this empty space.
![image](https://github.com/notes-org/notes-frontend/assets/942052/780963d7-394e-4567-8f29-5ab5847f34ea)

2024-03-21 01:20 UTC, berdal84 commented on src/utils/ApiClient.ts
> +                content: JSON.stringify(note.content) // TODO: allow an object instead of string on the backend API? Would be symetric
> JSON is transmitted as a string over HTTP. Thus, we will always need to call `JSON.stringify()`, or a similar function, before sending it to the API.

The http client (axios) does it for us, when we pass a stringified object the client may escape special characters and a simple string is sent.

2024-03-22 01:57 UTC, rjmello commented on src/utils/ApiClient.ts
> +                content: JSON.stringify(note.content) // TODO: allow an object instead of string on the backend API? Would be symetric
Yeah, I'm only pointing out that there is nothing to change on the back-end API, as the comment suggested, because JSON must always be converted to a string before it can be transmitted over HTTP. I don't have any preference on whether we rely on `axios` or `JSON.stringify()` for this.

2024-03-22 02:24 UTC, rjmello commented on src/utils/ApiClient.ts
> +                content: JSON.stringify(note.content) // TODO: allow an object instead of string on the backend API? Would be symetric
Ah, I see your point. The API expects a valid nested JSON object, represented as a string, but will reject strings that are not valid JSON. I'll add some logic on the back-end so we don't have to perform this extra serialization step.

2024-03-22 02:24 UTC, rjmello approved these changes

2024-03-22 02:33 UTC, merged