fix|refactor: fixes and rationalize UserContext and dependents
notes-org/notes-frontend pull request #9
Opened 2024-03-22 20:58 UTC by berdal84

- get user with getme() was not working properly
- signing-up now calls getme()
- username is well displayed in the nav bar
- cleaning namings & other various minor changes

2024-03-22 21:01 UTC, berdal84 commented on src/components/user/UserLoginButton.tsx
> +        {context.user ?
FYI: `user` has the guarantee to be an object when connected, otherwise it would be `null`.

2024-03-22 21:02 UTC, berdal84 commented on src/components/user/UserLoginButton.tsx
> -
FY: all this was too much code for nothing, I in-lined it in the "view".

2024-03-22 21:03 UTC, berdal84 commented on src/components/user/UserLoginForm.tsx
>  }
FY: no code is really using the signedUp flag, but it might be later (redirect to a given page).

2024-03-23 19:03 UTC, rjmello requested changes

2024-03-23 19:03 UTC, rjmello commented on src/components/user/UserLoginForm.tsx
> +        setStatus(user ? "Success" : "Unable to login, check your credentials an retry.");
```suggestion
        setStatus(user ? "Success" : "Unable to login; check your credentials and retry.");
```

2024-03-23 19:03 UTC, rjmello commented on src/components/user/UserLoginForm.tsx
> +        setStatus(user ? "Success" : "Unable to sign-up, login may be already in use.");
```suggestion
        setStatus(user ? "Success" : "Unable to sign up; you may already be logged in.");
```

2024-03-23 19:03 UTC, rjmello commented on src/contexts/UserContext.tsx
> +  errorMessage?: string;
I'd probably prefer Redux, but let's discuss later.

2024-03-23 19:03 UTC, rjmello commented on src/utils/ApiClient.ts
>              // grab the token from the local storaga and retry (see interceptors above)
```suggestion
            // Note that if it fails, the interceptor might be able to catch it and
            // grab the token from the local storage and retry (see interceptors above)
```

2024-03-23 23:12 UTC, berdal84 commented
Just committed your suggestions @rjmello

2024-03-25 02:00 UTC, rjmello approved these changes
Nice!

2024-03-25 03:29 UTC, merged